Repository Cryptonomic/Tezori, pull requests merged in 2018-07, with the labels that each got.

#168 Fix typo
  app/components/Home.js
Labels: enhancement

#170 Feat/nodes consolidation to one file
  .gitignore
  app/components/ActionPanel.js
  app/components/AddDelegateModal/index.js
  app/components/AddNodeModal/index.js
  app/components/Addresses.js
  app/components/CreateAccountSlide/index.js
  app/components/Delegate/index.js
  app/components/Home.css
  app/components/Home.js
  app/components/MessageBar.js
  app/components/Send.js
  app/components/SettingsController.js
  app/components/TopBar/index.js
  app/components/TotalBalance/index.js
  app/containers/Home/index.js
  app/containers/HomeAddAddress/index.js
  app/containers/HomeAddresses/index.js
  app/containers/HomeSettings/index.js
  app/containers/Login/index.js
  app/containers/LoginCreate/index.js
  app/containers/LoginImport/index.js
  app/reducers/message.duck.js
  app/reduxContent/createDelegate/thunks.js
  app/reduxContent/delegate/thunks.js
  app/reduxContent/index.js
  app/reduxContent/message/actions.js
  app/reduxContent/message/reducers.js
  app/reduxContent/message/thunks.js
  app/reduxContent/message/types.js
  app/reduxContent/nodes/actions.js
  app/reduxContent/nodes/reducers.js
  app/reduxContent/nodes/selectors.js
  app/reduxContent/nodes/thunks.js
  app/reduxContent/nodes/types.js
  app/reduxContent/sendTezos/thunks.js
  app/reduxContent/wallet/actions.js
  app/reduxContent/wallet/reducers.js
  app/reduxContent/wallet/selectors.js
  app/reduxContent/wallet/thunks.js
  app/reduxContent/wallet/types.js
  app/store/configureStore.dev.js
  app/store/configureStore.prod.js
  app/utils/nodes.js
  app/walletNodes.json
Labels: Done

#175 added fees for delegation, added custom field, and got ready for next…
  app/components/AddDelegateModal/index.js
  app/components/Delegate/index.js
  app/components/DelegateConfirmationModal/index.js
  app/components/Fees/index.js
  app/components/Send.js
  app/reduxContent/createDelegate/thunks.js
  app/reduxContent/delegate/thunks.js
  app/reduxContent/sendTezos/thunks.js
  app/utils/general.js
  package.json
  yarn.lock
Labels: Done

#270 Tests/redux/nodes
  package-lock.json
  test/reduxContent/nodes/actions.spec.js
  test/reduxContent/nodes/reducers.spec.js
Labels: In progress
